improve compat. issues handling

diff --git a/tests/cli b/tests/cli
--- a/tests/cli
+++ b/tests/cli
@@ -16,11 +16,13 @@ function reset() {
 	GENERAL="config.d/general.yml"
 	CLIENTS="config.d/clients.yml"
 	BOGONS="config.d/bogons.yml"
+	TITLE=""
+	SUB_TEST=""
 }
 
 function build_cmd() {
 	COMMAND="$1" ; shift
-	$AROUTESERVER $COMMAND --cfg $CFG_FILE --general $GENERAL --clients $CLIENTS --bogons $BOGONS $@ 2>&1
+	$AROUTESERVER $COMMAND --cfg $CFG_FILE --logging-level ERROR --general $GENERAL --clients $CLIENTS --bogons $BOGONS $@ 2>&1
 }
 
 function run_cmd() {
@@ -29,36 +31,46 @@ function run_cmd() {
 }
 
 function error() {
-	echo "$1"
+	echo "Failure during '$TITLE' at line $SUB_TEST: $1"
 	echo 1 > $RES_FILE
 }
 
 function must_contain() {
-	grep "$1" &>/dev/null || error "Fail: \"$1\" not found."
+	grep "$1" &>/dev/null || error "\"$1\" not found."
 }
 
 function must_not_contain() {
 	grep "$1" &>/dev/null
 
 	if [ $? -eq 0 ]; then
-		error "Fail: \"$1\" found."
+		error "\"$1\" found."
 	fi
 }
 
+# ---------------------------------------------
 # clients-from-euroix
 reset
+TITLE="clients-from-euroix"
 
 # 0.4 schema version:
+SUB_TEST="$LINENO"
 run_cmd "clients-from-euroix" --url https://my.ams-ix.net/api/v1/members.json 1 | must_contain "description: Akamai"
 # 0.5 schema version:
+SUB_TEST="$LINENO"
 run_cmd "clients-from-euroix" --url https://portal.lonap.net/apiv1/member-list/list 1 | must_contain "AS-APPLE"
 # 0.6 schema version:
+SUB_TEST="$LINENO"
 run_cmd "clients-from-euroix" --url https://www.swissix.ch/euroix/create-json-ixp-member-list.php 1 | must_contain "description: Microsoft"
 
+# ---------------------------------------------
 reset
+TITLE="OpenBGPD default config"
+SUB_TEST="$LINENO"
 build_cmd "openbgpd" | must_contain "ERROR Compatibility issue ID 'path_hiding'"
 
+# ---------------------------------------------
 reset
+TITLE="OpenBGPD large comms only"
 GENERAL="tests/var/general.yml"
 cat << EOF > $GENERAL
 cfg:
@@ -68,11 +80,21 @@ cfg:
     do_not_announce_to_peer:
       lrg: "rs_as:0:peer_as"
 EOF
-build_cmd "openbgpd" | must_contain "ERROR Compatibility issue ID 'large_communities'. The community 'do_not_announce_to_peer'"
-build_cmd "openbgpd" --target-version 6.0 | must_contain "ERROR Compatibility issue ID 'large_communities'. The community 'do_not_announce_to_peer'"
+
+EXP_ERR="ERROR Compatibility issue ID 'large_communities'. The community 'do_not_announce_to_peer'"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" | must_contain "$EXP_ERR"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --target-version 6.0 | must_contain "$EXP_ERR"
+
+SUB_TEST="$LINENO"
 build_cmd "openbgpd" --target-version 6.1 | must_not_contain "ERROR Compatibility issue ID 'large_communities'"
 
+# ---------------------------------------------
 reset
+TITLE="OpenBGPD blackhole filtering rewrite next-hop IPv6"
 GENERAL="tests/var/general.yml"
 cat << EOF > $GENERAL
 cfg:
@@ -82,10 +104,53 @@ cfg:
     policy_ipv6: 'rewrite-next-hop'
     rewrite_next_hop_ipv6: '2001:db8:1:1::66'
 EOF
-build_cmd "openbgpd" | must_contain "Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'. On OpenBSD < 6.1"
-build_cmd "openbgpd" --target-version 6.0 | must_contain "Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'. On OpenBSD < 6.1"
+
+EXP_ERR="Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'. On OpenBSD < 6.1"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" | must_contain "$EXP_ERR"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --target-version 6.0 | must_contain "$EXP_ERR"
+
+SUB_TEST="$LINENO"
 build_cmd "openbgpd" --target-version 6.1 | must_not_contain "Compatibility issue ID 'blackhole_filtering_rewrite_ipv6_nh'"
 
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --ignore-issues "blackhole_filtering_rewrite_ipv6_nh" | must_not_contain "'do_not_announce_to_peer'"
+
+# ---------------------------------------------
+reset
+TITLE="OpenBGPD large comms"
+GENERAL="tests/var/general.yml"
+cat << EOF > $GENERAL
+cfg:
+  rs_as: 999
+  router_id: "192.0.2.2"
+  communities:
+    do_not_announce_to_peer:
+      std: "0:peer_as"
+      lrg: "rs_as:0:peer_as"
+EOF
+
+EXP_ERR="'do_not_announce_to_peer' has been configured to be implemented using also the large community '999:0:peer_as';"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" | must_contain "$EXP_ERR"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --target-version 6.0 | must_contain "$EXP_ERR"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --target-version 6.1 | must_not_contain "'do_not_announce_to_peer'"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --target-version 6.0 --ignore-issues "large_communities" | must_not_contain "'do_not_announce_to_peer'"
+
+SUB_TEST="$LINENO"
+build_cmd "openbgpd" --ignore-issues "large_communities" | must_not_contain "'do_not_announce_to_peer'"
+
+# ---------------------------------------------
 ERROR=`cat $RES_FILE`
 if [ $ERROR -eq 1 ]; then
 	echo "Done! ERRORS FOUND"
