tests and utils

diff --git a/utils/test_config b/utils/test_config
--- a/utils/test_config
+++ b/utils/test_config
@@ -39,16 +39,31 @@ elif [ "$1" == "bird6" ]; then
 elif [ "$1" == "openbgpd60" -o "$1" == "openbgpd61" ]; then
 	virsh \
 		start arouteserver_$1
-	echo "When started..."
-	echo "scp -i ~/.ssh/arouteserver -o StrictHostKeyChecking=no $2 root@192.0.2.2:/etc/bgpd.conf"
-	echo "ssh -i ~/.ssh/arouteserver -o StrictHostKeyChecking=no root@192.0.2.2"
-	echo "/etc/rc.d/bgpd stop ; bgpd -dn && /etc/rc.d/bgpd start"
-	echo "bgpctl"
 	echo ""
 	virsh list
 	echo ""
 	while true; do
-		ssh -i ~/.ssh/arouteserver -o StrictHostKeyChecking=no -o ConnectTimeout=5 -o ServerAliveInterval=10 root@192.0.2.2 echo "Up!"
+		echo "Waiting for server reachability... "
+		ssh -i ~/.ssh/arouteserver -o StrictHostKeyChecking=no -o ConnectTimeout=5 -o ServerAliveInterval=10 -q root@192.0.2.2 echo "Up!"
+		if [ $? -eq 0 ]; then
+			echo "VM is up & running"
+
+			echo "Copying configuration..."
+			scp -i ~/.ssh/arouteserver -o StrictHostKeyChecking=no -q $2 root@192.0.2.2:/etc/bgpd.conf
+			if [ $? -ne 0 ]; then
+				echo "ERROR while copying configuration"
+				exit 1
+			fi
+
+			echo "Testing config on the VM... "
+			ssh -i ~/.ssh/arouteserver -o StrictHostKeyChecking=no -q root@192.0.2.2 "/etc/rc.d/bgpd stop ; bgpd -dn"
+			if [ $? -eq 0 ]; then
+				echo "SUCCESS"
+			else
+				echo "FAILURE"
+			fi
+			exit
+		fi
 		sleep 5
 	done
 else
